### ISSUE TITLE
issue : Dynamic Server Usage - No-store Fetch Error in Champion Rotation API

### ISSUE THREAD

**Issue by yuna-c** [yuna-c/lolDex#2]
```javascript
   Generating static pages (0/8)  [    ]데이터 패치 중 에러가 발생 했어요! B [Error]: Dynamic server usage: no-store fetch https://kr.api.riotgames.com/lol/platform/v3/champion-rotations /api/rotation
    at C:\Users\82109\Desktop\lol-dex\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36008
    at C:\Users\82109\Desktop\lol-dex\node_modules\next\dist\server\lib\trace\tracer.js:140:36
    at NoopContextManager.with (C:\Users\82109\Desktop\lol-dex\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:7062)
    at ContextAPI.with (C:\Users\82109\Desktop\lol-dex\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:518)
    at NoopTracer.startActiveSpan (C:\Users\82109\Desktop\lol-dex\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:18093)
    at ProxyTracer.startActiveSpan (C:\Users\82109\Desktop\lol-dex\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:18854)
    at C:\Users\82109\Desktop\lol-dex\node_modules\next\dist\server\lib\trace\tracer.js:122:103
    at NoopContextManager.with (C:\Users\82109\Desktop\lol-dex\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:7062)
    at ContextAPI.with (C:\Users\82109\Desktop\lol-dex\node_modules\next\dist\compiled\@opentelemetry\api\index.js:1:518)
    at NextTracerImpl.trace (C:\Users\82109\Desktop\lol-dex\node_modules\next\dist\server\lib\trace\tracer.js:122:28) {
  description: 'no-store fetch https://kr.api.riotgames.com/lol/platform/v3/champion-rotations /api/rotation',
  digest: 'DYNAMIC_SERVER_USAGE'
``` 
#1 a7838fc1696f7a8921c30c7867ef35b92fe3981c

**Comment by yuna-c** [comment]
no-store를 사용하는 경우 Next.js에서 정적 페이지 생성을 할 수 없어 빌드 과정에서 에러 발생 가능성이 있음. no-store는 매번 데이터를 다시 가져오는 옵션으로 정적 빌드를 지원하지 않는 동적 데이터를 다룰 때 사용되며, 정적 페이지 생성 시 이러한 동적 요청을 허용하지 않기 때문에 빌드 타임에 에러가 발생함.

revalidate 사용 이유:

- 정적 생성과 주기적인 갱신: revalidate: 86400은 24시간마다 페이지를 새로 생성하여 정적 생성 방식으로 데이터를 제공하면서도 일정 주기로 업데이트 가능. 이를 통해 배포 후에도 24시간마다 데이터를 최신 상태로 유지 가능.

- 성능 최적화: no-store 사용 시 매번 서버에서 데이터를 가져와 비용과 응답 시간이 증가. revalidate는 일정 시간 동안 캐시하여 설정한 시간 이후에만 갱신하므로 성능과 비용 측면에서 유리.

- 따라서 no-store는 서버 리소스를 많이 사용하며 정적 생성이 불가능하므로, 주기적으로 데이터를 갱신하고 성능 최적화를 위해 revalidate를 사용하는 것이 적합.
